{ pkgs, ... }:
{
  gtk = {
    enable = true;

    theme = {
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };

    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };

    gtk2.extraConfig = "gtk-application-prefer-dark-theme = true\n";

    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = 1;
      gtk-cursor-theme-size = 8;
    };

    gtk4.extraConfig = {
      gtk-application-prefer-dark-theme = 1;
      gtk-theme-name = "adw-gtk3-dark";
      gtk-icon-theme-name = "Papirus-Dark";
      gtk-cursor-theme-size = 8;
    };
  };

  # NOTE: gtk-4.0/settings.ini is generated by home-manager from the
  # gtk.* options above — do NOT add a manual xdg.configFile for it here.
  # A manual block concatenates with the generated one (double [Settings]
  # header, see issue) and fights over gtk-theme-name. Keep theme pins in
  # gtk4.extraConfig instead.

  dconf.settings = {
    "org/gnome/desktop/interface" = {
      gtk-theme = "adw-gtk3-dark";
      icon-theme = "Papirus-Dark";
      color-scheme = "prefer-dark";
    };
  };
  home.pointerCursor = {
    enable = true;
    name = "Bibata-Modern-Ice";
    gtk.enable = true;
    x11.enable = true;
    size = 8;
    package = pkgs.bibata-cursors;
  };
  qt = {
    enable = true;
    platformTheme.name = "gtk3";
  };
}
